export const GET_CONTEXT_LIST_SUCCESSFUL = 'GET_CONTEXT_LIST_SUCCESSFUL';
export const GET_NAMESPACE_LIST_SUCCESSFUL = 'GET_NAMESPACE_LIST_SUCCESSFUL';
export const GET_RESOURCE_TYPES_LIST_SUCCESSFUL =
  'GET_RESOURCE_TYPES_LIST_SUCCESSFUL';
export const GET_RESOURCE_DESCRIPTION_SUCCESSFUL =
  'GET_RESOURCE_DESCRIPTION_SUCCESSFUL';
export const CLEAR_RESOURCE_DESCRIPTION = 'CLEAR_RESOURCE_DESCRIPTION';
export const CHANGE_CONTEXT = 'CHANGE_CONTEXT';
export const CHANGE_NAMESPACES = 'CHANGE_NAMESPACES';
export const CHANGE_RESOURCE_TYPES = 'CHANGE_RESOURCE_TYPES';
export const GET_RESOURCE_SUCCESSFUL = 'GET_RESOURCE_SUCCESSFUL';
